name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        git clone --recurse-submodules https://github.com/daniel-kelley/xtg
        make -C xtg
    - name: make
      run: make -C xtg
    - name: make check
      run: |
        ls
        ls xtg
        make -C xtg clean
        make -C xtg SANITIZE=address SANLIBS=-lasan check
