name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        sudo apt-get install libboost-dev
        sudo apt-get install libboost-program-options-dev
        git clone --recurse-submodules https://github.com/daniel-kelley/xtg
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: find
      run: find . -type f
    - name: make
      run: make -C xtg
    - name: make check
      run: |
        make -C xtg clean
        make -C xtg SANITIZE=address WARN= SANLIBS=-lasan check
